# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: exam1
app: exam1-app
org: fernandescauep



provider:
  name: aws
  runtime: nodejs10.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - sqs:SendMessage
        - sqs:GetQueueUrl
        - sqs:ReceiveMessage
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:ChangeMessageVisibility
      Resource: "arn:aws:sqs:us-east-1:918810475415:exam1"
    - Effect: "Allow"
      Action:
        - "sqs:ListQueues"
      Resource: "arn:aws:sqs:us-east-1:918810475415:*"
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:918810475415:table/exam1"

functions:
  sender:
    handler: sender.handler
    events:
      - http:
          path: v1/sender
          method: post
  receiver:
    handler: receiver.handler
    events:
      - sqs:
          arn: "arn:aws:sqs:us-east-1:918810475415:exam2"
          batchSize: 1

# resources:
#   Resources:
#     MyQueue:
#       Type: "AWS::SQS::Queue"
#       Properties:
#         QueueName: "exam1"
#     MyTable:
#       Type: AWS::DynamoDB::Table
#       Properties:
#         TableName: exam1
#         AttributeDefinitions:
#           - AttributeName: Id
#             AttributeType: S
#         KeySchema:
#           - AttributeName: Id
#             KeyType: HASH
#         BillingMode: PAY_PER_REQUEST
